---
title: "Task_1_Prodigy"
author: "Hermela Seltanu"
date: "2024-11-12"
output: html_document
---

```{r warning=FALSE, message=FALSE}
library(tidyverse)
```

```{r warning=FALSE, message=FALSE}
# Read the csv file
kenya_pop <- read_csv("kenya-population-distibution-2019-census.csv")
# Remove the first row
kenya_popu <- kenya_pop[-1, ]
# Viewing the first rows 
head(kenya_popu)
```

```{r}
# Checking the structure of the dataset
glimpse(kenya_popu)
```

```{r}
library(ggplot2)
library(reshape2)

# Melting the dataset for plotting
melted_data <- melt(kenya_popu, id.vars = "County", measure.vars = c("Male", "Female", "Intersex"))

# Creating a grouped bar chart
ggplot(melted_data, aes(x = County, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge", width = 1) +  
  scale_fill_manual(values = c("Male" = "blue", "Female" = "yellow", "Intersex" = "purple")) +  
  labs(title = "Gender-wise Population Distribution in Kenyan Counties (2019)",
       x = "County", y = "Population",
       fill = "Gender") +
  theme_minimal(base_size = 14) +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),  
        axis.title = element_text(size = 12),  
        legend.position = "top") 


```

```{r}
# Identify the top 5 counties with the largest total population
top_5_counties <- kenya_popu %>%
  arrange(desc(Total)) %>%
  head(5)

# Melt the dataset for easier plotting (long format)
melted_top_5 <- melt(top_5_counties, id.vars = "County", 
                     measure.vars = c("Male", "Female", "Intersex"))

# Create a stacked bar chart for the top 5 counties
ggplot(melted_top_5, aes(x = County, y = value, fill = variable)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("Male" = "blue", "Female" = "yellow", "Intersex" = "purple")) +
  labs(title = "Population Distribution in Top 5 Most Populous Kenyan Counties (2019)",
       x = "County", y = "Population",
       fill = "Gender") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


